baseURL = "https://snikt.net/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Andreas Happe"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
#theme = "mainroad"
theme = "hugo-theme-minos"
enableGitInfo = false
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
hasCJKLanguage = false
paginate = 10
disqusShortname = "signalnoise"
googleAnalytics = "UA-2424774-4"

[permalinks]
  post = "blog/:year/:month/:day/:title/"

[author]
  name = "Andreas Happe"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "Book: Web-Security"
  weight = 12
  identifier = "websec_book"
  url = "/websec"

[[menu.main]]
  name = "Book: SecOps"
  weight = 12
  identifier = "secops_book"
  url = "/secops"

[[menu.main]]
  name = "Life"
  weight = 12
  identifier = "life"
  url = "/categories/life"
[[menu.main]]
  name = "Tech"
  weight = 12
  identifier = "tech"
  url = "/categories/tech"
[[menu.main]]
  name = "Security"
  weight = 12
  identifier = "security"
  url = "/categories/security"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"
#[[menu.main]]
#  name = "Categories"
#  weight = 40
#  identifier = "categories"
#  url = "/categories/"

[params]
  readmore = true

  keywords = ["Andreas Happe", "Happe","Ruby on Rails", "Security", "Tech"]
  description = "Andreas Happe sometimes blogs about developmen, life or security."

  archivePaginate = 50
  showArchiveCount = false
  dateFormatToUse = "2006-01-02"
  moreMeta = false
  highlightInClient = false
  smartToc = true

# See https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true      # 12.214.31.144 -> 12.214.31.0
  [privacy.youtube]
    privacyEnhanced = true
